# Generated by Django 3.1.6 on 2021-02-03 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField()),
                ('action', models.IntegerField(choices=[(1, 'Allow'), (2, 'Block')], default=1)),
                ('comment', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
